[package]
name = "pbpctrl"
authors = ["Maximilian Luz <m@mxnluz.io>"]
version = "0.1.5"
edition = "2021"
license = "MIT/Apache-2.0"
description = "Command-line utility for controlling Google Pixel Buds Pro"
repository = "https://github.com/qzed/pbpctrl"

[dependencies]
anyhow = "1.0.75"
bluer = { version = "0.16.1", features = ["bluetoothd", "rfcomm"] }
clap = { version = "4.4.6", features = ["derive"] }
futures = "0.3.28"
maestro = { path = "../libmaestro" }
tokio = { version = "1.33.0", features = ["rt", "macros", "signal"] }
tracing = "0.1.39"
tracing-subscriber = "0.3.17"

[build-dependencies]
bluer = { version = "0.16.1" }
clap = { version = "4.4.6", features = ["derive"] }
clap_complete = "4.4.3"
maestro = { path = "../libmaestro" }
