[package]
name = "pbpctrl"
authors = ["Maximilian Luz <m@mxnluz.io>"]
version = "0.1.2"
edition = "2021"
license = "MIT/Apache-2.0"
description = "Command-line utility for controlling Google Pixel Buds Pro"
repository = "https://github.com/qzed/pbpctrl"

[dependencies]
anyhow = "1.0.70"
bluer = { version = "0.15.7", features = ["bluetoothd", "rfcomm"] }
clap = { version = "4.2.3", features = ["derive"] }
futures = "0.3.28"
maestro = { path = "../libmaestro" }
tokio = { version = "1.27.0", features = ["rt", "macros", "signal"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"

[build-dependencies]
bluer = { version = "0.15.7" }
clap = { version = "4.2.3", features = ["derive"] }
clap_complete = "4.2.0"
maestro = { path = "../libmaestro" }
