[package]
name = "maestro"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.2"
bytes = "1.3.0"
log = "0.4.17"
tokio = "1.23.0"
tokio-util = { version = "0.7.4", features = ["codec"] }
uuid = "1.2.2"
