[package]
name = "maestro"
authors = ["Maximilian Luz <m@mxnluz.io>"]
version = "0.1.1"
edition = "2021"
license = "MIT/Apache-2.0"
description = "Maestro protocol client implementation for controlling Google Pixel Buds Pro"
repository = "https://github.com/qzed/pbpctrl"

[dependencies]
arrayvec = "0.7.2"
bytes = "1.4.0"
futures = "0.3.28"
num_enum = "0.6.1"
prost = "0.11.9"
tokio = "1.27.0"
tokio-util = { version = "0.7.7", features = ["codec"] }
tracing = "0.1.37"
uuid = "1.3.1"

[build-dependencies]
prost-build = "0.11.9"

[dev-dependencies]
anyhow = "1.0.70"
bluer = { version = "0.15.7", features = ["bluetoothd", "rfcomm"] }
futures = "0.3.28"
pretty-hex = "0.3.0"
tokio = { version = "1.27.0", features = ["rt", "macros", "signal"] }
tracing-subscriber = "0.3.16"
