[package]
name = "maestro"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.2"
bytes = "1.3.0"
futures = "0.3.25"
num_enum = "0.5.7"
prost = "0.11.3"
tokio = "1.23.0"
tokio-util = { version = "0.7.4", features = ["codec"] }
tracing = "0.1.37"
uuid = "1.2.2"

[build-dependencies]
prost-build = "0.11.4"

[dev-dependencies]
anyhow = "1.0.68"
bluer = { version = "0.15.3", features = ["bluetoothd", "rfcomm"] }
futures = "0.3.25"
pretty-hex = "0.3.0"
tokio = { version = "1.23.0", features = ["rt", "macros", "signal"] }
tracing-subscriber = "0.3.16"
