[package]
name = "gfps"
authors = ["Maximilian Luz <m@mxnluz.io>"]
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"
description = "Google Fast Pair Service (GFPS) protocol client library"
repository = "https://github.com/qzed/pbpctrl"

[dependencies]
bytes = "1.4.0"
num_enum = "0.6.1"
smallvec = { version = "1.10.0", features = ["union"] }
tokio = "1.27.0"
tokio-util = { version = "0.7.7", features = ["codec"] }
uuid = "1.3.1"

[dev-dependencies]
bluer = { version = "0.15.7", features = ["bluetoothd", "rfcomm"] }
futures = "0.3.28"
pretty-hex = "0.3.0"
tokio = { version = "1.27.0", features = ["rt", "macros"] }
