[package]
name = "gfps"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.3.0"
num_enum = "0.5.7"
tokio = "1.23.0"
tokio-util = { version = "0.7.4", features = ["codec"] }
uuid = "1.2.2"

[dev-dependencies]
bluer = { version = "0.15.3", features = ["bluetoothd", "rfcomm"] }
futures = "0.3.25"
tokio = { version = "1.23.0", features = ["rt", "macros"] }
